micronaut:
  application:
    name: pixGrpc

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: ${DATABASE_URL:`jdbc:mysql://localhost:3306/pix_grpc?useTimezone=true&serverTimezone=UTC`}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:Administrator*}
#    dialect: org.hibernate.dialect.MySQL8Dialect

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

itau:
  contas:
    url: 'http://localhost:9091'


bcb:
  pix:
    url: 'http://localhost:8082'